<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foundation for Sites</title>
    <link rel="stylesheet" href="<?= App::config('url')?>public/css/foundation.css">
    <link rel="stylesheet" href="<?= App::config('url')?>public/css/app.css">
</head>

<body>

    <div class="grid-container">
        <div class="grid-x grid-padding-x">
            <div class="large-12 cell">
                <?= $sadrzaj ?>
            </div>
        </div>

    </div>


    <script src="<?=App::config('url')?>public/js/vendor/jquery.js"></script>
    <script src="<?=App::config('url')?>public/js/vendor/what-input.js"></script>
    <script src="<?=App::config('url')?>public/js/vendor/foundation.js"></script>
    <script src="<?=App::config('url')?>public/js/app.js"></script>
</body>

</html>