<form class="log-in-form" action="<?= App::config('url');?>prijava/autorizacija" method="post">
  <h4 class="text-center">Unesite pristupne podatke</h4>
  <label>Email
    <input type="email" name="email" 
    value="<?=$email?> "placeholder="netko@nesto.com">
  </label>
  <label>Lozinka
    <input type="password" name="password" placeholder="Lozinka">
  </label>
  
  <p><input type="submit" class="button expanded" value="Prijava"></input></p>
  <?= $poruka?>
</form>



